config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # get 'users/follow'
  resources :tweets do
    post 'likes', to: 'tweets#likes'
    post 'retweet', to: 'tweets#retweet'
  end
  devise_for :users
  get 'home/index'
  get 'all_tweets', to: 'home#all_tweets', as: 'all_tweets'
  
  post 'follow/:friend_id', to: 'users#follow', as: 'users_follow'
  # get 'api/news' 

  scope '/api' do
    get '/news', to: 'api#news', as: 'api_news'
    get '/:date1/:date2', to: 'api#tweets_by_date', as: 'api_tweets_by_date'
    post '/tweets', to: 'api#create_tweet', as: 'api_create_tweet'
  end
  # Ex:- scope :active, -> {where(:active => true)}

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
# include ActionView::Helpers::UrlHelper

class Tweet < ApplicationRecord
  before_save :add_hashtags


  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, :through => :likes, :source => :user

  validates :content, presence: true

  paginates_per 10

  scope :tweets_for_me, ->(user) { where(user_id: user.arr_friends_id_and_me) }

  def add_hashtags
    new_content = ""
    self.content.split(" ").each do |word|
      if word.start_with?("#")
        word_clean = word.gsub("#", " ")
        new_content += "<a href='/?search=#{word_clean}'>#{word}</a>"+" "
        # new_content += link_to(word, Rails.application.routes.url_helpers.root_path+"?search="+word_clean)+" "
      else
        new_content += word + " "
      end
    end
    self.content = new_content
  end

  def like_icon(user)
    if self.is_liked?(user)
      'fas fa-heart text-danger'
    else
      'far fa-heart text-muted'
    end
  end

  def is_liked?(user)
    self.liking_users.include?(user)
  end

  def like(user)
    Like.create(user: user, tweet: self)
  end

  def remove_like(user)
    Like.where(user: user, tweet: self).destroy_all
  end

  def count_rt
    Tweet.where(rt_ref: self.id).count
  end

  def is_retweet?
    self.rt_ref.present?
  end

  def tweet_ref
    Tweet.find(self.rt_ref)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :delete_friends
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :liked_tweets, :through => :likes, :source => :tweet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  def is_following?(friend_id)
    self.friends.where(:friend_id => friend_id).exists?
  end

  def delete_friends
    Friend.where(:friend_id => id).destroy_all
  end

  def arr_friends_id
    friends.pluck(:friend_id)
  end

  def arr_friends_id_and_me
    friends.pluck(:friend_id).push(id)
  end

  def friend_count
    friends.count
  end

  def tweets_count
    tweets.count
  end

  def likes_given
    likes.count
  end

  def retweets_given
    tweets.where.not(rt_ref: nil).count
  end

  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user&.valid_password?(password) ? user : nil
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  def news
    # render json: Tweet.last(5)
    tweets = Tweet.last(50)
    hash = tweets.map do |tweet|
      {
        id: tweet.id,
        content: tweet.content,
        user_id: tweet.user_id,
        like_count: tweet.likes.count,
        retweets_count: tweet.count_rt,
        retweeted_from: (tweet.rt_ref.nil? ? '-' : tweet.rt_ref)
      }
    end
    render json: hash.to_json
  end

  def tweets_by_date
    date1 = Date.parse(params[:date1])
    date2 = Date.parse(params[:date2])

    render json: Tweet.where(created_at: (date1..date2))
  end

  def create_tweet
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if user.nil?
      render json: { error: 'Invalid credentials' }
      return
    end
    
    @tweet = Tweet.new(tweet_params)
    @tweet.user = user
    if @tweet.save
      render json: @tweet, status: :created
    else
      render json: @tweet.errors, status: :unprocessable_entity
    end
  end

  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def authenticate_admin!
        redirect_to new_user_session_path unless (current_user && current_user.admin)
    end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      @tweets = Tweet.tweets_for_me(current_user).where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
    else
      @tweets = Tweet.where("content LIKE ?", "%#{params[:search]}%").order(created_at: :desc).page params[:page]
    end

    @tweet = Tweet.new
  end

  def all_tweets
    @tweets = Tweet.order(created_at: :desc).page params[:page]
    @tweet = Tweet.new
    render "index"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :set_current_tweet, only: %i[likes retweet]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  def likes
    if @tweet.is_liked?(current_user)
      @tweet.remove_like(current_user)
    else
      @tweet.like(current_user)
    end
    redirect_to root_path
  end

  def retweet
    Tweet.create(content: @tweet.content, user_id: current_user.id, rt_ref: @tweet.id)
    redirect_to root_path
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        # format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.html { redirect_to root_path, alert: "Say something!" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def set_current_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def follow
    if current_user.is_following?(params[:friend_id])
      Friend.where(user_id: current_user.id, friend_id: params[:friend_id]).delete_all
    else
      Friend.create(user_id: current_user.id, friend_id: params[:friend_id])
    end
    redirect_to root_path
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row">
    <% if user_signed_in? %>
        <%= render 'tweets/form', tweet: @tweet %>
    <% end %>

    

    <% @tweets.each do |tweet| %>
        <%= render 'tweets/single_tweet', tweet: tweet %>
    <% end %>
    <br>
    <%# paginate @tweets %>
    <%= link_to_next_page @tweets, 'Mostrar mas' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Say it!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/78e321ae9f.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% if notice || alert %>
      <div class="alert alert-<%= alert ? 'danger' : 'success' %> text-center" role="alert">
        <%= notice %>
        <%= alert %>
      </div>      
    <% end %>

    <div class="container pt-5">
      <div class="row pt-5">
        <div class="col-md-9 col-sm-12 m-auto">
          <%= yield %>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container">
      <%= image_tag "splashlogo.png", class: 'navimage' %>
      <a class="navbar-brand navlogocustom" href="<%= root_path %>">Say it!</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-auto text-right">
          <li><%= form_tag(root_path, method: :get) do %>
            <div class="d-inline ml-auto">
                <%= text_field_tag(:search, params[:search], class: 'w-50 form-control d-inline') %>
                <%= button_tag type: 'submit', class: "ml-2 btn btn-primary" do %>
                    <i class="fas fa-search"></i>
                <% end %>
                <%= link_to "Limpiar", root_path, :class => 'btn btn-info ml-2' %>
            </div>
          <% end %></li>
        <% if user_signed_in? %>
          <li class="nav-item active"><%= link_to "Hola #{current_user.username}!", root_path, class: 'nav-link' %> <span class="sr-only">(current)</span></li>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to 'Admin', admin_root_path, class: 'nav-link' %></li>
          <% end %>
          <li class="nav-item"><%= link_to 'Explorar', all_tweets_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Cerrar sesión', destroy_user_session_path, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Registro', new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true, :class => 'w-100 mb-3') do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <b class="text-muted"><i class="fas fa-arrow-circle-down"></i> Say something here! <i class="fas fa-arrow-circle-down"></i></b>
    <br>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="text-right">
    <%= form.submit "Say it!", class: 'btn btn-info sayitbutton' %>
  </div>
<% end %>

app/views/tweets/_single_tweet.html.erb
<div class="col-12 shadow custom-bg customround mt-4">
    <div class="row">
        <div class="col-3 p-0 pr-2 m-0"><div class="customsize"><%= image_tag (tweet.user.avatar), class: "h-100 w-100 avatar-in-tweet rounded-circle" %></div></div>
        <div class="col-7 p-2">
            <%= link_to "<small class='text-muted'><i class='fas fa-comment-dots'></i> ".html_safe+time_ago_in_words(tweet.created_at)+" ago.</small>".html_safe, tweet %>
            <br/>
            <div class="w-100 px-2">
                <small><i class="fas fa-comment-alt text-muted"></i> <%= tweet.user.username %> says: </small><br/>

                <p><i><%= tweet.content.html_safe %></i></p>
            </div>
        </div>
        <br>
        <div class="col-2 text-right py-2">
            <div>
                <% if user_signed_in? && current_user != tweet.user %>
                    <% if current_user.is_following?(tweet.user_id) %>
                        <%= link_to "<i class='fas fa-user-times text-danger'></i>".html_safe, users_follow_path(tweet.user_id), method: :post %>
                    <% else %>
                        <%= link_to "<i class='fas fa-user-plus text-success'></i>".html_safe, users_follow_path(tweet.user_id), method: :post %>
                    <% end %>
                <% else %>
                    <br/>
                <% end %>
            </div>
            <% if user_signed_in? %>                
                <div>
                    <%= link_to "<i class='#{tweet.like_icon(current_user)}'></i>".html_safe, tweet_likes_path(tweet), method: :post %>
                    <small class="text-danger"><%= tweet.likes.count %></small>
                </div>
                <div>
                    <%= link_to "<i class='fas fa-retweet text-#{tweet.count_rt > 0 ? "success" : "muted"}'></i>".html_safe, tweet_retweet_path(tweet), method: :post %>
                    <small class="text-primary"><%= tweet.count_rt %></small>
                    <% if tweet.is_retweet? %>
                        <br/>
                        <small class='text-muted'><%= link_to 'Retweets!', tweet.tweet_ref %></small>
                    <% else %>
                        <br/>
                        <p></p>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.content %></td>
        <td><%= tweet.user %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
<p class="my-5">
  <strong>@<%= @tweet.user.username %> said:</strong><br>
  <i>"<%= @tweet.content.html_safe %>"</i>
</p>

<% if @tweet.liking_users.count == 0 %>
  <small>No one likes this :( </small>
<% else %>    
  <small>
    Liked by: <br>
    <% @tweet.liking_users.each do |user| %>
      <%= image_tag(user.avatar, class: 'avatar-in-tweet rounded', title: user.username, data: { toggle: 'tooltip', placement: 'bottom' }) %>
    <% end %>
  </small>
<% end %>
</div>
<br>
<div class="text-center">
<%= link_to 'Back', root_path, class: 'btn-sm btn-primary' %>
</div>

app/views/users/follow.html.erb
<h1>Users#follow</h1>
<p>Find me in app/views/users/follow.html.erb</p>